name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *'   # runs once a day (midnight UTC)
  workflow_dispatch:       # allows manual run

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get TryHackMe badge
        run: |
          curl -L "https://tryhackme.com/api/v2/badges/public-profile?userPublicId=3965018" --output thm-badge.svg

      - name: Commit and push updated badge
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add thm-badge.svg
          git commit -m "update: refreshed TryHackMe badge" || echo "No changes"
          git push
